name: CI
on: [pull_request, push]
jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python:
          - "3.10"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install prerequisites
        run:
          python -m pip install mypy
      - name: Type check
        run:
          python -m mypy -p synth
